Update mavgen_c to python3
ArduPilot/pymavlink pull request #1000
Opened 2024-12-24 05:50 UTC by jmackay2

Most of the code was already compatible with python3 except for the small change for iteritems. The builtins and print_function were put in to make it python3 compatible, so those are no longer necessary.

2025-01-14 14:32 UTC, bobpaul requested changes
I'm not a project maintainer, but from reading other comments on github, I understand pymavlink is not yet ready to intentionally remove python2 support.

`python-future` at least partially requires (for running the tests for sure) lib2to3 which was removed in python13. Removing pymavlink's dependence on the `future` module seems reasonable and certainly for this file can be done without breaking python2 compatibility.

2025-01-22 15:15 UTC, bobpaul commented
I had read that discussion, too, and it wasn't clear to me they had made a decision. Peter's comment a few months ago in #976 look clear to me that they still don't want us to intentionally remove Python2 support, just don't jump through hoops to maintain support:

>We're not going out of our way to support Python2 any more - if it breaks it breaks.

> But we are also not going out of our way to kill it right now in pymavlink. That day may come - and it will be a good day!

One of the things to keep in mind is that a lot of use of mavlink is on embedded devices in the air. While it's easy to get python3 support on our computers, getting python3 on an out of production intel edison or some other product that never had an official BSP for any embedded linux new enough to include python3 could be challenging for some users. (That's a situation I was in about 3 years ago).

2025-01-28 21:31 UTC, tridge commented
I think we are ready to be py3 only now

2025-02-04 16:33 UTC, bobpaul approved these changes
In light of tridge's comment, I think this looks fine as is and you can ignore my previous suggestions.

2025-03-05 04:57 UTC, merged

2025-03-05 04:57 UTC, peterbarker commented
Merged, thanks!