Mode:add Plane AUTOLAND mode
ArduPilot/pymavlink pull request #1002
Opened 2024-12-30 20:32 UTC by Hwurzburg

2024-12-30 23:15 UTC, peterbarker requested changes

2024-12-30 23:15 UTC, peterbarker commented on mavutil.py
> +    26 : 'AUTLOAND',
```suggestion
    26 : 'AUTOLAND',
```

2024-12-31 00:11 UTC, Hwurzburg commented on mavutil.py
> +    26 : 'AUTLOAND',
duh

2024-12-31 00:50 UTC, peterbarker requested changes

2024-12-31 00:50 UTC, peterbarker commented on mavutil.py
> +    26 : 'AUT0LAND',
```suggestion
    26 : 'AUTOLAND',
```

2024-12-31 01:04 UTC, Hwurzburg commented on mavutil.py
> +    26 : 'AUT0LAND',
double duh

2024-12-31 22:52 UTC, peterbarker approved these changes

2024-12-31 22:53 UTC, merged