mavutil: Return mode as 'Mode(msg.custom_mode)' for high-latency streams
ArduPilot/pymavlink pull request #779
Opened 2023-02-16 09:59 UTC by dernatsch

Before, when reading high-latency messages that came from PX4, mavutil threw an exception because after the check for PX4, `msg.base_mode` was read immediately. It was not regarded that the `HIGH_LATENCY2` message does not contain a `base_mode` field.

This introduces a fix where the mode string for _all_ `HIGH_LATENCY2` messages is returned as `Mode(msg.custom_mode)`.

2023-03-02 08:01 UTC, peterbarker commented
This also looks like we will no longer map the base mode to a string on ArduPilot.

Could you put your two new lines just within the PX4 bloc there, please - just stop us reading those attributes within that block if the message is a `HIGH_LATENCY2`

Apologies for the breakage - we really should have picked this up.

@stephendade FYI

2023-03-02 09:50 UTC, dernatsch commented
@peterbarker Just changed it. Is this what you had in mind? :)

2023-03-02 20:32 UTC, stephendade commented
FYI in ArduPilot, we do send the ``base_mode`` in the ``custom0`` field of ``HIGH_LATNENCY2``, as we need ``base_mode`` to determine if the vehicle's armed.

2023-03-03 03:38 UTC, peterbarker approved these changes
LGTM

2023-03-03 03:39 UTC, peterbarker requested changes
Ah, sorry - still have  the f-string :-/

2023-03-04 18:26 UTC, dernatsch commented
@peterbarker No worries, changed it to the way it's done at the bottom of the function. Hope it's alright now. :)

2023-03-06 03:02 UTC, merged